export const AUTH_MESSAGES = {
  REGISTER_SUCCESS: "Registration successful. Please verify your email.",
  LOGIN_SUCCESS: "Welcome back",
  LOGOUT_SUCCESS: "Logout successful",
  EMAIL_VERIFIED: "Email verified successfully",
  EMAIL_ALREADY_VERIFIED: "Email is already verified",
  VERIFICATION_SENT: "Verification email sent successfully",
  PASSWORD_RESET_SENT: "Password reset link sent to your email",
  PASSWORD_RESET_SUCCESS: "Password reset successful",
  PASSWORD_CHANGED: "Password changed successfully",
  TOKEN_REFRESHED: "Token refreshed successfully",

  // Errors
  INVALID_CREDENTIALS: "Invalid email or password",
  EMAIL_EXISTS: "Email already registered",
  EMAIL_DOESNOT_EXISTS: "Email doesn't exit",
  PHONE_EXISTS: "Phone number already registered",
  USER_NOT_FOUND: "User not found",
  INVALID_TOKEN: "Invalid or expired token",
  ACCOUNT_SUSPENDED: "Your account has been suspended",
  EMAIL_NOT_VERIFIED: "Please verify your email first",
  INCORRECT_PASSWORD: "Current password is incorrect",
  SAME_PASSWORD: "New password cannot be same as old password",
  MAX_ATTEMPTS_EXCEEDED: "Too many login attempts. Please try again later.",
};